### ISSUE TITLE
/app Directory Missing From Container

### ISSUE THREAD

**Issue by jmwright** [sabrehagen/freecad-to-step#1]
The readme states that there should be an `/app` directory present in the container. I don't see that container after building the pipeline. I do see the `input` and `output` directories though.

**Comment by jmwright** [comment]
I'm not sure why it didn't do this before, but after adding my user to the docker group and restarting, I get this when I try to run the image.
```bash
/bin/sh: 1: /app/entrypoint.sh: not found
```

**Comment by sabrehagen** [comment]
Yes, you're totally right.

In the `run-pipeline.sh` script I'm [mounting](https://github.com/stemn/stemn-ci/blob/master/run-pipeline.sh#L14) the `./provider/stage/app` folder to `/app` in the container. Running the container as-is will not have the `/app` folder as it does not exist in the container image, but once the `run-pipeline.sh` script is run and the mount is created, the `/app` folder will exist.

I'm guessing you're doing `docker run stemn-ci` to get the `/app/entrypoint.sh: not found` message. This means you're running the container without the mount, and thus the `entrypoint.sh` script doesn't exist.

You can override the [`CMD` command](https://github.com/stemn/stemn-ci/blob/master/Dockerfile#L16) by running `docker run -it stemn-ci bash`. The last parameter is the command to run, in this case `bash`, which takes priority over `CMD` in the `Dockerfile`.

**Comment by jmwright** [comment]
Sorry, I'm a newbie with Docker. I was trying `docker run stemn-ci:latest`. Your command line doesn't throw the error, but `/app` still isn't there. Should that command be mounting `/app` or is there another step I'm missing?

**Comment by jmwright** [comment]
Ok, I see now. You're saying that since I'm running it locally the mount won't be there. Overriding the CMD command just suppresses the error.

**Comment by sabrehagen** [comment]
Yes, that's right. If you run `docker run -it -v /tmp/app:/app stemn-ci` that will mount the `/tmp/app` directory on your machine into the container at the `/app` location.

By overriding the `CMD` command you're avoiding the error by changing the command executed when the container starts. It's no longer executing the default command of `/app/entrypoint.sh`. If you want to mount your directory **and** override your container start command, you can run `docker run -it -v /tmp/app:/app stemn-ci bash`.
